stages:
  - build
  - deploy
build:
  stage: build
  script:
    - docker build -t strixthekiet/vdt24-web:$CI_COMMIT_TAG .
    - docker push strixthekiet/vdt24-web:$CI_COMMIT_TAG

deploy:
  stage: deploy
  script:
    - sed -i "s/tag: .*/tag: $CI_COMMIT_TAG/": values.yaml
    - git add  values.yaml
    - git commit -m "Updated to $CI_COMMIT_TAG"
    - git push

